---
- hosts: all
  become: true
  vars:
    ansible_ssh_private_key_file: /Users/edidiongetuk/.ssh/id_ed25519

  tasks:
    - name: Create skeleton directory
      file:
        path: /etc/skel
        state: directory

    - name: Copy nice-script.sh to skeleton directory
      copy:
        src: nice-script.sh
        dest: /etc/skel/nice-script.sh
        mode: 0755

    - name: Create user john
      user:
        name: john
        home: /better-place/john
        uid: 1234
        createhome: yes

    - name: Allow user john to run whoami with sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'john ALL=(ALL:ALL) NOPASSWD: /usr/bin/whoami'
        validate: 'visudo -cf %s'

    - name: Install Tmux and vim packages
      apt:
        name:
          - tmux
          - vim
        state: present

    - name: Download and install Terraform CLI dependencies
      apt:
        name:
          - gnupg
          - lsb-release
        state: present

    - name: Add HashiCorp GPG key
      shell: |
        wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add HashiCorp apt repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

    - name: Update apt cache
      apt:
        update_cache: yes
      changed_when: false

    - name: Install Terraform CLI
      apt:
        name: terraform
        state: present
