name: Build and Publish Image
on: [push]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Image
        run: docker build -t ghcr.io/${{ github.repository }}:1 .

      - name: Publish Image
        run: docker push ghcr.io/${{ github.repository }}:1
