name: Build and Publish Image
on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 19 * * SAT"

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Image
        run: docker build -t ghcr.io/${{ github.repository }}:$(git rev-parse --short ${{ github.sha }}) .
    
      - name: Publish Image
        run: docker push ghcr.io/${{ github.repository }}:$(git rev-parse --short ${{ github.sha }}) 